global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using DatabaseServices.Models;
global using Models.Account;
//using Azure;
global using Mapper;
global using Microsoft.EntityFrameworkCore;
global using Models;